<?php
// filepath: d:\Programming\oop\MiniProject\oopMiniProject\database\seeders\RestaurantSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Restaurant;
use App\Models\District;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        // Get Kandy district
        $kandy = District::where('slug', 'kandy')->first();

        if (!$kandy) {
            $this->command->error('❌ Kandy district not found. Please run DistrictSeeder first.');
            return;
        }

        // Clear existing restaurants for Kandy
        Restaurant::where('district_id', $kandy->id)->delete();

        $restaurants = [
            [
                'name' => 'Temple View Coffee House',
                'slug' => 'temple-view-coffee-house',
                'type' => 'cafe',
                'description' => 'Cozy café with temple views, serving excellent coffee, fresh pastries, and light meals. Perfect for a relaxing break after temple visit.',
                'image_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
                    'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
                    'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800',
                ],
                'rating' => 4.6,
                'reviews_count' => 89,
                'cuisine_type' => ['Coffee & Tea', 'Breakfast'],
                'price_range' => 2,
                'opening_time' => '06:00:00',
                'closing_time' => '20:00:00',
                'phone' => '+94 81 222 3344',
                'address' => '45 Peradeniya Road, Kandy',
                'location' => '250m from Temple of the Tooth',
                'latitude' => 7.2946,
                'longitude' => 80.6403,
                'facilities' => ['wifi', 'ac', 'outdoor_seating', 'garden'],
                'tags' => ['Tourist Friendly'],
                'famous_for' => 'Ceylon Tea & Pastries',
                'is_active' => true,
            ],
            [
                'name' => 'Kandy Garden Café',
                'slug' => 'kandy-garden-cafe',
                'type' => 'restaurant',
                'description' => 'Traditional Sri Lankan restaurant serving authentic rice and curry with fresh local ingredients. Popular with both locals and tourists.',
                'image_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
                ],
                'rating' => 4.2,
                'reviews_count' => 156,
                'cuisine_type' => ['Local Cuisine', 'Vegetarian Friendly'],
                'price_range' => 2,
                'opening_time' => '07:00:00',
                'closing_time' => '21:00:00',
                'phone' => '+94 81 223 4455',
                'address' => '123 Dalada Veediya, Kandy Central',
                'location' => '180m from Temple of the Tooth',
                'latitude' => 7.2945,
                'longitude' => 80.6380,
                'facilities' => ['ac', 'wifi', 'cards', 'parking'],
                'tags' => ['Family Friendly'],
                'famous_for' => 'Rice & Curry',
                'is_active' => true,
            ],
            [
                'name' => 'Malini\'s Hopper Station',
                'slug' => 'malinis-hopper-station',
                'type' => 'food_stall',
                'description' => 'Authentic street food stall famous for fresh hoppers and kottu roti. A must-try local experience right near the temple entrance.',
                'image_url' => 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
                ],
                'rating' => 4.1,
                'reviews_count' => 234,
                'cuisine_type' => ['Street Food', 'Local Favorite'],
                'price_range' => 1,
                'opening_time' => '06:00:00',
                'closing_time' => '23:00:00',
                'phone' => '+94 77 123 4567',
                'address' => 'Temple Street, Near Main Entrance',
                'location' => '320m from Temple of the Tooth',
                'latitude' => 7.2940,
                'longitude' => 80.6410,
                'facilities' => ['takeaway', 'cash_only'],
                'tags' => ['Budget Friendly'],
                'famous_for' => 'Egg Hoppers',
                'is_active' => true,
            ],
            [
                'name' => 'The Empire Café',
                'slug' => 'the-empire-cafe',
                'type' => 'cafe',
                'description' => 'Colonial-era café serving traditional English breakfast, afternoon tea, and international cuisine in a historic setting.',
                'image_url' => 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800',
                    'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
                ],
                'rating' => 4.5,
                'reviews_count' => 178,
                'cuisine_type' => ['Continental', 'English'],
                'price_range' => 3,
                'opening_time' => '07:00:00',
                'closing_time' => '22:00:00',
                'phone' => '+94 81 222 5566',
                'email' => 'info@empirecafe.lk',
                'website' => 'https://empirecafe.lk',
                'address' => '21 Temple Street, Kandy',
                'location' => '400m from Temple of the Tooth',
                'latitude' => 7.2935,
                'longitude' => 80.6420,
                'facilities' => ['wifi', 'ac', 'english_menu', 'cards', 'parking'],
                'tags' => ['Historic'],
                'famous_for' => 'Afternoon Tea',
                'is_active' => true,
            ],
            [
                'name' => 'Balaji Dosai',
                'slug' => 'balaji-dosai',
                'type' => 'restaurant',
                'description' => 'Popular South Indian restaurant known for its crispy dosas, idlis, and vadas. Pure vegetarian menu with authentic Tamil flavors.',
                'image_url' => 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800',
                ],
                'rating' => 4.3,
                'reviews_count' => 267,
                'cuisine_type' => ['South Indian', 'Vegetarian'],
                'price_range' => 1,
                'opening_time' => '06:30:00',
                'closing_time' => '22:00:00',
                'phone' => '+94 81 224 5678',
                'address' => '56 Kotugodella Veediya, Kandy',
                'location' => '450m from Temple of the Tooth',
                'latitude' => 7.2930,
                'longitude' => 80.6425,
                'facilities' => ['ac', 'vegetarian', 'family_friendly'],
                'tags' => ['Vegetarian', 'Budget Friendly'],
                'famous_for' => 'Masala Dosa',
                'is_active' => true,
            ],
            [
                'name' => 'Lake View Restaurant',
                'slug' => 'lake-view-restaurant',
                'type' => 'restaurant',
                'description' => 'Fine dining restaurant with stunning views of Kandy Lake. Serves Sri Lankan and international cuisine in an elegant atmosphere.',
                'image_url' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
                    'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
                ],
                'rating' => 4.7,
                'reviews_count' => 145,
                'cuisine_type' => ['Sri Lankan', 'International', 'Seafood'],
                'price_range' => 3,
                'opening_time' => '11:00:00',
                'closing_time' => '23:00:00',
                'phone' => '+94 81 223 7788',
                'email' => 'reservations@lakeview.lk',
                'website' => 'https://lakeview-kandy.lk',
                'address' => '8 Lake Round, Kandy',
                'location' => '500m from Temple of the Tooth',
                'latitude' => 7.2925,
                'longitude' => 80.6395,
                'facilities' => ['wifi', 'ac', 'parking', 'cards', 'english_menu', 'lake_view', 'bar'],
                'tags' => ['Fine Dining', 'Scenic View'],
                'famous_for' => 'Seafood & Lake Views',
                'is_active' => true,
            ],
            [
                'name' => 'Muslim Hotel',
                'slug' => 'muslim-hotel-kandy',
                'type' => 'restaurant',
                'description' => 'Traditional Muslim restaurant famous for its biryani, kottu, and authentic Sri Lankan Muslim cuisine. A local favorite for decades.',
                'image_url' => 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800',
                ],
                'rating' => 4.4,
                'reviews_count' => 312,
                'cuisine_type' => ['Sri Lankan Muslim', 'Halal'],
                'price_range' => 1,
                'opening_time' => '07:00:00',
                'closing_time' => '22:30:00',
                'phone' => '+94 81 222 8899',
                'address' => 'Main Bazaar, Kandy',
                'location' => '550m from Temple of the Tooth',
                'latitude' => 7.2920,
                'longitude' => 80.6430,
                'facilities' => ['halal', 'takeaway', 'family_friendly'],
                'tags' => ['Local Favorite', 'Budget Friendly'],
                'famous_for' => 'Chicken Biryani',
                'is_active' => true,
            ],
            [
                'name' => 'White House Restaurant',
                'slug' => 'white-house-restaurant',
                'type' => 'restaurant',
                'description' => 'Multi-cuisine restaurant offering Chinese, Sri Lankan, and Western dishes. Popular for family dining with spacious seating.',
                'image_url' => 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
                ],
                'rating' => 4.0,
                'reviews_count' => 198,
                'cuisine_type' => ['Chinese', 'Sri Lankan', 'Western'],
                'price_range' => 2,
                'opening_time' => '10:00:00',
                'closing_time' => '22:00:00',
                'phone' => '+94 81 223 9900',
                'address' => '33 Dalada Veediya, Kandy',
                'location' => '280m from Temple of the Tooth',
                'latitude' => 7.2942,
                'longitude' => 80.6385,
                'facilities' => ['ac', 'wifi', 'parking', 'cards', 'family_friendly'],
                'tags' => ['Family Friendly'],
                'famous_for' => 'Fried Rice & Noodles',
                'is_active' => true,
            ],
            [
                'name' => 'Sharon Inn',
                'slug' => 'sharon-inn',
                'type' => 'restaurant',
                'description' => 'Rooftop restaurant with panoramic city views. Serves Sri Lankan rice and curry, short eats, and refreshing beverages.',
                'image_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
                ],
                'rating' => 4.3,
                'reviews_count' => 87,
                'cuisine_type' => ['Local Cuisine'],
                'price_range' => 2,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'phone' => '+94 81 224 1122',
                'address' => '67 Yatinuwara Street, Kandy',
                'location' => '600m from Temple of the Tooth',
                'latitude' => 7.2915,
                'longitude' => 80.6440,
                'facilities' => ['rooftop', 'wifi', 'city_view'],
                'tags' => ['Scenic View'],
                'famous_for' => 'Rooftop Dining',
                'is_active' => true,
            ],
            [
                'name' => 'Slightly Chilled Lounge',
                'slug' => 'slightly-chilled-lounge',
                'type' => 'cafe',
                'description' => 'Trendy café and lounge with a relaxed vibe. Great for coffee, smoothies, burgers, and Western-style light meals.',
                'image_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
                ],
                'rating' => 4.4,
                'reviews_count' => 76,
                'cuisine_type' => ['Café', 'Western'],
                'price_range' => 2,
                'opening_time' => '08:00:00',
                'closing_time' => '22:00:00',
                'phone' => '+94 81 223 4433',
                'address' => '12 Rajapihilla Mawatha, Kandy',
                'location' => '650m from Temple of the Tooth',
                'latitude' => 7.2910,
                'longitude' => 80.6445,
                'facilities' => ['wifi', 'ac', 'outdoor_seating', 'english_menu'],
                'tags' => ['Modern'],
                'famous_for' => 'Smoothie Bowls',
                'is_active' => true,
            ],
            [
                'name' => 'Olde Empire Hotel Restaurant',
                'slug' => 'olde-empire-hotel-restaurant',
                'type' => 'restaurant',
                'description' => 'Historic hotel restaurant with colonial charm. Serves buffet-style Sri Lankan meals and international dishes.',
                'image_url' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
                ],
                'rating' => 4.1,
                'reviews_count' => 134,
                'cuisine_type' => ['International', 'Sri Lankan'],
                'price_range' => 3,
                'opening_time' => '06:30:00',
                'closing_time' => '22:00:00',
                'phone' => '+94 81 223 2284',
                'email' => 'info@oldeempire.lk',
                'website' => 'https://oldeempire.lk',
                'address' => '21 Temple Street, Kandy',
                'location' => '350m from Temple of the Tooth',
                'latitude' => 7.2938,
                'longitude' => 80.6415,
                'facilities' => ['wifi', 'ac', 'parking', 'cards', 'buffet', 'bar'],
                'tags' => ['Historic', 'Hotel Restaurant'],
                'famous_for' => 'Buffet Lunch',
                'is_active' => true,
            ],
            [
                'name' => 'Devon Restaurant',
                'slug' => 'devon-restaurant',
                'type' => 'restaurant',
                'description' => 'Budget-friendly restaurant serving tasty rice and curry, kottu, and fried rice. Popular among locals and backpackers.',
                'image_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
                'images' => [
                    'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
                ],
                'rating' => 3.9,
                'reviews_count' => 203,
                'cuisine_type' => ['Sri Lankan', 'Chinese'],
                'price_range' => 1,
                'opening_time' => '07:00:00',
                'closing_time' => '21:00:00',
                'phone' => '+94 81 222 3355',
                'address' => '44 Dalada Veediya, Kandy',
                'location' => '300m from Temple of the Tooth',
                'latitude' => 7.2943,
                'longitude' => 80.6390,
                'facilities' => ['takeaway', 'family_friendly'],
                'tags' => ['Budget Friendly'],
                'famous_for' => 'Rice & Curry Plate',
                'is_active' => true,
            ],
        ];

        $created = 0;
        foreach ($restaurants as $restaurantData) {
            $restaurantData['district_id'] = $kandy->id;

            try {
                Restaurant::create($restaurantData);
                $created++;
            } catch (\Exception $e) {
                $this->command->error("Error creating {$restaurantData['name']}: " . $e->getMessage());
            }
        }

        $this->command->info("✅ Successfully created {$created} restaurants near Temple of the Tooth");
    }
}
