
{{-- filepath: resources/views/admin/report.blade.php --}}
@extends('admin.layouts.app')

@section('title', 'System Report')

@section('content')
<div style="max-width: 900px; margin: 0 auto;">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px;">
        <h1 style="font-size: 28px; font-weight: 600; color: #333;">System Report</h1>
        <button onclick="window.print()" style="background: #667eea; color: white; padding: 12px 24px; border: none; border-radius: 8px; cursor: pointer;">
            🖨️ Print Report
        </button>
    </div>

    <div style="background: white; padding: 40px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.05);">
        <div style="text-align: center; margin-bottom: 40px;">
            <h2 style="color: #667eea; margin-bottom: 10px;">TravelEase System Report</h2>
            <p style="color: #999;">Generated on {{ $report['generated_at'] }}</p>
        </div>

        <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 40px;">
            <div style="background: #f9f9f9; padding: 20px; border-radius: 8px;">
                <h4 style="color: #999; font-size: 13px; margin-bottom: 10px;">Total Countries</h4>
                <div style="font-size: 32px; font-weight: bold; color: #667eea;">{{ $report['total_countries'] }}</div>
            </div>

            <div style="background: #f9f9f9; padding: 20px; border-radius: 8px;">
                <h4 style="color: #999; font-size: 13px; margin-bottom: 10px;">Total Districts</h4>
                <div style="font-size: 32px; font-weight: bold; color: #48bb78;">{{ $report['total_districts'] }}</div>
            </div>

            <div style="background: #f9f9f9; padding: 20px; border-radius: 8px;">
                <h4 style="color: #999; font-size: 13px; margin-bottom: 10px;">Total Attractions</h4>
                <div style="font-size: 32px; font-weight: bold; color: #ed8936;">{{ $report['total_attractions'] }}</div>
            </div>

            <div style="background: #f9f9f9; padding: 20px; border-radius: 8px;">
                <h4 style="color: #999; font-size: 13px; margin-bottom: 10px;">Total Accommodations</h4>
                <div style="font-size: 32px; font-weight: bold; color: #9f7aea;">{{ $report['total_accommodations'] }}</div>
            </div>

            <div style="background: #f9f9f9; padding: 20px; border-radius: 8px;">
                <h4 style="color: #999; font-size: 13px; margin-bottom: 10px;">Total Users</h4>
                <div style="font-size: 32px; font-weight: bold; color: #4299e1;">{{ $report['total_users'] }}</div>
            </div>

            <div style="background: #f9f9f9; padding: 20px; border-radius: 8px;">
                <h4 style="color: #999; font-size: 13px; margin-bottom: 10px;">Total Reviews</h4>
                <div style="font-size: 32px; font-weight: bold; color: #f6ad55;">{{ $report['total_reviews'] }}</div>
            </div>
        </div>

        <div style="text-align: center; padding-top: 40px; border-top: 2px solid #e0e0e0;">
            <p style="color: #999; font-size: 14px;">This report was automatically generated by TravelEase Admin System</p>
        </div>
    </div>
</div>

<style>
@media print {
    .top-nav, .sidebar, button { display: none !important; }
    .main-content { padding: 0 !important; }
}
</style>
@endsection
